### ISSUE TITLE
[BUG] DLS performance has regressed with new serialization format

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3776]
**What is the bug?**
Some users of OpenSearch have seen a performance decrease associated with DLS queries.  Larger DLS queries (more characters) 
have a larger impact.

**How can one reproduce the bug?**
1. Checkout my fork with the repro `git clone https://github.com/peternied/security.git`
2. Checkout the most recent security plugin version with the new tests `git checkout dls-perf`
3. Execute the new tests `./gradlew integrationTest --tests org.opensearch.security.DlsTests.testDlsLargerQueryScenarios -x jacocoTestReport`
4. Open the test report `./build/reports/tests/integrationTest/classes/org.opensearch.security.DlsTests.html`
5. View the standard output
```
Creating 5 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 11.07, 17, 8, 1.67
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 8.45, 17, 6, 1.64
Finished checks in 5282ms
Creating 50 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 13.68, 21, 10, 2.27
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 252.04, 538, 228, 31.20
Finished checks in 30905ms
Creating 100 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 12.56, 19, 10, 1.78
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 984.57, 1027, 916, 21.51
Finished checks in 107909ms
```

**What is the expected behavior?**
After the `DLS_ONLY_LONG_VALUE` is added, the AVG should not jump up so much.

**Do you have any additional context?**
You can collect measures from the 2.3 build by running `git checkout dls-perf` from that branch to collect numbers from that version
- https://github.com/opensearch-project/security/compare/main...peternied:security:dls-perf
- https://github.com/opensearch-project/security/compare/2.3...peternied:security:2.3-dls-perf

This issue was introduced in the following PR which did improve serialization in many scenarios, but seems to be impacting DLS queries as stored in headers.
- https://github.com/opensearch-project/security/pull/2802

**Comment by peternied** [comment]
I've tracked the problem to this serialization code that seems to take **~1ms** in 2.3, whereas it takes **~13ms** in 2.11
https://github.com/opensearch-project/security/blob/6b8a3e494c7933b93f6ee4f1a7956b728ed48a43/src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java#L455-L461

**Comment by krishna-ggk** [comment]
Is there JDK version difference between 2.3 and 2.11 in the test?

**Comment by peternied** [comment]
It uses the default JDK on your machine to specify, set `export JAVA_HOME=` to run the tests with different JDKs

**Comment by peternied** [comment]
<summary>

Previous testing wasn't properly switching to using only the custom vs jdk (de)serializers which lead to incomplete results, its clear that the custom serialization process is producing the issue with the 981ms respond time compared to 63ms.

<details>

### Test methodology

Modified `Base64Helper.java` by deleting other reference to `Base64JDKHelper` or `Base64CustomHelper` to force serialization process.

Ran with `./gradlew integrationTest --tests org.opensearch.security.DlsTests.testDlsLargerQueryScenarios -x jacocoTestReport`


https://github.com/opensearch-project/security/blob/6b8a3e494c7933b93f6ee4f1a7956b728ed48a43/src/main/java/org/opensearch/security/support/Base64Helper.java#L33-L47

#### Custom Serialization Enabled Results

```
Creating 5 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 10.45, 18, 8, 1.75
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 8.85, 20, 6, 1.92
Finished checks in 5305ms
Creating 50 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 21.29, 310, 10, 34.49
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 249.17, 278, 225, 9.03
Finished checks in 31874ms
Creating 100 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 12.75, 21, 10, 1.97
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 981.53, 1050, 950, 17.50
Finished checks in 107491ms
```

#### JDK Serialization Enabled Results

```
Creating 5 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 11.67, 20, 9, 1.90
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 8.62, 13, 6, 1.20
Finished checks in 5354ms
Creating 50 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 15.4, 23, 12, 2.31
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 33.01, 81, 21, 11.79
Finished checks in 9024ms
Creating 100 indices with 1 document
User, Count, Avg, Max, Min, Std ms reader, 100, 17.73, 30, 14, 3.03
Attached READER with role DLS_ONLY_LONG_VALUE
User, Count, Avg, Max, Min, Std ms reader, 100, 63.54, 69, 59, 1.88
Finished checks in 11701ms
```

</details>

</summary>

**Comment by peternied** [comment]
@parasjain1 - can you look into this can be setting can be disabled or fixed?  I think this would justify a patch release - happy to help drive that process.

**Comment by cwperks** [comment]
Would it make sense to update the `GENERIC` case of [serialization](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/support/Base64CustomHelper.java#L94-L97)/[de-serialization](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/support/Base64CustomHelper.java#L127-L129) to use JDK serialization?

i.e.

```
For Serialization

case GENERIC:
    streamOutput.writeByte((byte) CustomSerializationFormat.GENERIC.id);
    streamOutput.writeBytes(SerializationUtils.serialize(object));
    break;

For Deserialization

case GENERIC:
    obj = SerializationUtils.deserialize(streamInput.readByteArray());
    break;
```

**Comment by parasjain1** [comment]
In response to @cwperks's suggestion to use JDK serde in case of `GENERIC`, this will introduce complexity with regards to handling an additional serialization protocol which might be temporary until [#11430](https://github.com/opensearch-project/OpenSearch/issues/11430) is resolved.

I've concluded that we can introduce a way to enable / disable custom serialization. The idea is to allow users with limited  or no DLS/FLS use case to continue leveraging the faster custom serialization protocol other scenarios.

Below is the approach that I'll be implementing. This assumes that the changes will be part of a patch release version `2.11.1`


* Introduce a new `boolean` node attribute and a dynamic cluster setting  -  `plugins.security.custom_serialization.enabled`. It is to be noted that with this change the ** `2.11.1` nodes will have this node attribute present while the `2.11.0` nodes won’t.
    * This property will allow users to opt for the type of serialization protocol they want to use.
    * Default will be `false`  for now, i.e. use JDK serialization. Can be changed to `true` once we’ve resolved this regression issue.
* Requests sent via `2.11.1` nodes will have an additional `boolean` header `plugins.security.custom_serialization.enabled` with the value same as the node attribute. These will be used during message reception as we won’t have a reference to the remote node that has sent the message.



* For **requests sent** from the `2.11.1` nodes to -
    * Case 1 : a node running OS version < `2.11`
        * always use JDK to serialize the headers [this check is already present]
    * Case 2: a node running *OS* `2.11.0`
        * while sending a request we have reference to the remote node and can check for the presence of the node attribute `plugins.security.custom_serialization.enabled`. In this case the attribute will not be present on the remote node. Thus, we serialize via custom serialization.
    * Case 3:  a node running *OS >=* `2.11.1`  
        * The remote node will have the attribute `plugins.security.custom_serialization.enabled` set - if the attribute value is `true` serialize via custom serialization, JDK otherwise. 
* For **requests received** on the `2.11.1` nodes from -
    * Case 1 : a node running OS version < `2.11`
        * always use JDK to deserialize the headers [this check is already present]
    * Case 2: a node running OS  *`2.11.0`*
        * Request header `plugins.security.custom_serialization.enabled` will be absent, always use custom serialization
    * Case 3: a node running OS >=  `2.11.1` 
        *  Request header  `plugins.security.custom_serialization.enabled` will be present - if header value is `true` deserialize via custom serialization, JDK otherwise

**Comment by parasjain1** [comment]
Have raised a PR - https://github.com/opensearch-project/security/pull/3789

**Comment by scrawfor99** [comment]
[Triage] Marking this as triaged since it is being addressed by Paras' PR.

**Comment by nibix** [comment]
It's not a quick fix, but I just wanted to point out that https://github.com/opensearch-project/security/issues/3870 would fix this, as the concept proposes a new DLS/FLS implementation which no longer relies on the serialization of DLS/FLS configurations.

**Comment by pmarjou22** [comment]
I confirm the performance problem for DLS  is still existing in version 2.16. We had to rollback to 2.10, this is a blocker for our scenarios in production, the opensearch cluster completely unusable after upgrade once non administrator start using the application.

We are able to reproduce the problem locally on a vanilla opensearch docker

Using 100 indexes (sample ecommerce clones with 2K documents) , we confirmed with JMeter the same behavior that explained in this bug

Version  | Admin Rights (Call / Sec)  | 	Limited Rights via DLS (Call / Sec)
2.10	| 33.2	| 21.7
2.13	| 32.6	| 10.2
2.14	| 46.65     | 3.3
2.15	| 45          | 3.1
2.16	| 36.2       | 3.2

dls filter : 
`{"bool":{"filter":[{"match_all":{}},{"bool":{"should":[{"match_phrase":{"currency":"EUR"}},{"match_phrase":{"currency":"molestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestiemolestie"}}],"minimum_should_match":1}}]}}

POST path /sample_data_ecommerce/_search?request_cache=false
POST body 
`{"size":500,"query":{"bool":{"filter":[{"bool":{"should":[{"match_phrase":{"currency":"EUR"}},{"match_phrase":{"currency":"${randomVar}"}},{"match_phrase":{"currency":"CAD"}},{"match_phrase":{"currency":"POR"}},{"match_phrase":{"currency":"REE"}},{"match_phrase":{"currency":"DSS"}},{"match_phrase":{"currency":"FDF"}},{"match_phrase":{"currency":"KJK"}},{"match_phrase":{"currency":"NBV"}},{"match_phrase":{"currency":"AZE"}},{"match_phrase":{"currency":"WXW"}},{"match_phrase":{"currency":"JDS"}},{"match_phrase":{"currency":"MLA"}},{"match_phrase":{"currency":"TRE"}}],"minimum_should_match":1}}],"must_not":[{"match_phrase":{"customer_full_name":"Frances Davidson"}},{"match_phrase":{"customer_first_name":"Frances"}},{"match_phrase":{"user":"elyssa"}}]}}}`
`

**Comment by peternied** [comment]
@pmarjou22 Thanks for posting, could you create a new issue in this repo with these details?  It looks like there might have been a second performance impacting issues as on 2.10 -> 2.11 the drop is explained with #2802, however, the drop from 2.13 -> 2.14 might be another issue.

Could you help us determine the root cause by run jprofiler on the OpenSearch v2.16+ node processing the request to point towards a root cause?
